import {
  AvailableEquipment,
  MeasurementType,
  PhysicalLimitation,
  TrainingGoal,
} from '../model/types';

export interface ExerciseDefinition {
  id: string;
  name: string;
  muscleGroup: 'CHEST' | 'BACK' | 'LEGS' | 'SHOULDERS' | 'ARMS' | 'CORE' | 'CARDIO' | 'FULL_BODY';
  measurementType: MeasurementType;
  equipmentRequired: AvailableEquipment;
  instructions: string;
  alternative: string;
  contraindications: PhysicalLimitation[];
  suitableGoals: TrainingGoal[];
  experienceMin: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';
  defaultReps: {
    strength: number;
    hypertrophy: number;
    fitness: number;
    endurance: number;
    calisthenics: number;
    sport: number;
  };
  defaultRestSeconds: number;
}

export const EXERCISE_LIBRARY: ExerciseDefinition[] = [
  // ==========================================
  // BODYWEIGHT ONLY (Home — No Equipment)
  // ==========================================
  {
    id: 'bw-squat',
    name: 'Bodyweight Squat',
    muscleGroup: 'LEGS',
    measurementType: 'REPS',
    equipmentRequired: 'NONE',
    instructions: 'Hips back and down, knees track over toes, maintain upright chest and neutral spine.',
    alternative: 'Chair or Box-Assisted Squats',
    contraindications: ['KNEE_PAIN'],
    suitableGoals: ['STRENGTH', 'MUSCLE_GROWTH', 'GENERAL_FITNESS', 'ENDURANCE', 'CALISTHENICS', 'SPORT_PERFORMANCE'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 6, hypertrophy: 12, fitness: 15, endurance: 20, calisthenics: 10, sport: 12 },
    defaultRestSeconds: 60,
  },
  {
    id: 'bw-reverse-lunge',
    name: 'Reverse Lunge',
    muscleGroup: 'LEGS',
    measurementType: 'REPS',
    equipmentRequired: 'NONE',
    instructions: 'Step rearward with control, lower back knee gently toward floor, keep front shin vertical.',
    alternative: 'Static Split Squats without stepping',
    contraindications: ['KNEE_PAIN'],
    suitableGoals: ['STRENGTH', 'MUSCLE_GROWTH', 'GENERAL_FITNESS', 'ENDURANCE', 'CALISTHENICS', 'SPORT_PERFORMANCE'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 6, hypertrophy: 10, fitness: 12, endurance: 16, calisthenics: 8, sport: 10 },
    defaultRestSeconds: 60,
  },
  {
    id: 'bw-glute-bridge',
    name: 'Glute Bridge',
    muscleGroup: 'LEGS',
    measurementType: 'REPS',
    equipmentRequired: 'NONE',
    instructions: 'Feet flat on floor hip-width apart, drive through heels, lock hips out by squeezing glutes.',
    alternative: 'Elevated Back Bridge or Short-Range Hip Lifts',
    contraindications: [],
    suitableGoals: ['STRENGTH', 'MUSCLE_GROWTH', 'GENERAL_FITNESS', 'ENDURANCE', 'CALISTHENICS', 'SPORT_PERFORMANCE'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 8, hypertrophy: 15, fitness: 15, endurance: 25, calisthenics: 12, sport: 15 },
    defaultRestSeconds: 45,
  },
  {
    id: 'bw-calf-raises',
    name: 'Standing Calf Raises',
    muscleGroup: 'LEGS',
    measurementType: 'REPS',
    equipmentRequired: 'NONE',
    instructions: 'Stand tall with feet parallel, press through balls of feet, hold peak contraction for 1 second.',
    alternative: 'Seated Foot Plantar Flexion',
    contraindications: [],
    suitableGoals: ['GENERAL_FITNESS', 'ENDURANCE', 'MUSCLE_GROWTH', 'SPORT_PERFORMANCE'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 10, hypertrophy: 15, fitness: 20, endurance: 25, calisthenics: 15, sport: 20 },
    defaultRestSeconds: 45,
  },
  {
    id: 'bw-wall-sit',
    name: 'Wall Sit Isometric',
    muscleGroup: 'LEGS',
    measurementType: 'DURATION',
    equipmentRequired: 'NONE',
    instructions: 'Press back flat against wall, slide down until thighs are parallel to ground, engage quads.',
    alternative: 'High-Angle 45-Degree Wall Sit',
    contraindications: ['KNEE_PAIN'],
    suitableGoals: ['GENERAL_FITNESS', 'ENDURANCE', 'CALISTHENICS', 'SPORT_PERFORMANCE'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 30, hypertrophy: 40, fitness: 35, endurance: 50, calisthenics: 45, sport: 40 },
    defaultRestSeconds: 60,
  },
  {
    id: 'bw-push-up',
    name: 'Standard Push-Up',
    muscleGroup: 'CHEST',
    measurementType: 'REPS',
    equipmentRequired: 'NONE',
    instructions: 'Hands shoulder-width apart, rigid core plank, lower chest to one inch from floor with 45-degree elbow path.',
    alternative: 'Incline Hands-Elevated Push-Ups or Knee Push-Ups',
    contraindications: ['WRIST_DISCOMFORT', 'SHOULDER_IMPINGEMENT'],
    suitableGoals: ['STRENGTH', 'MUSCLE_GROWTH', 'GENERAL_FITNESS', 'ENDURANCE', 'CALISTHENICS', 'SPORT_PERFORMANCE'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 6, hypertrophy: 10, fitness: 12, endurance: 18, calisthenics: 10, sport: 12 },
    defaultRestSeconds: 60,
  },
  {
    id: 'bw-knee-push-up',
    name: 'Knee Push-Up (Floor Assisted)',
    muscleGroup: 'CHEST',
    measurementType: 'REPS',
    equipmentRequired: 'NONE',
    instructions: 'Knees grounded, straight line from knees to shoulders, controlled descent with chest touch.',
    alternative: 'Wall Press-Ups',
    contraindications: ['WRIST_DISCOMFORT'],
    suitableGoals: ['GENERAL_FITNESS', 'ENDURANCE', 'STRENGTH'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 8, hypertrophy: 12, fitness: 15, endurance: 20, calisthenics: 10, sport: 12 },
    defaultRestSeconds: 45,
  },
  {
    id: 'bw-pike-push-up',
    name: 'Pike Push-Up',
    muscleGroup: 'SHOULDERS',
    measurementType: 'REPS',
    equipmentRequired: 'NONE',
    instructions: 'Elevate hips into inverted V-shape, lower top of head gently toward floor between hands, press through shoulders.',
    alternative: 'Forearm Downward Dog Push',
    contraindications: ['SHOULDER_IMPINGEMENT', 'WRIST_DISCOMFORT'],
    suitableGoals: ['STRENGTH', 'CALISTHENICS', 'MUSCLE_GROWTH', 'SPORT_PERFORMANCE'],
    experienceMin: 'INTERMEDIATE',
    defaultReps: { strength: 5, hypertrophy: 8, fitness: 10, endurance: 12, calisthenics: 8, sport: 8 },
    defaultRestSeconds: 75,
  },
  {
    id: 'bw-superman',
    name: 'Prone Superman Hold & Pulse',
    muscleGroup: 'BACK',
    measurementType: 'REPS',
    equipmentRequired: 'NONE',
    instructions: 'Lie face down, simultaneously lift chest and quads off floor by contracting glutes and upper back.',
    alternative: 'Alternating Prone Arm/Leg Lifts',
    contraindications: ['LOWER_BACK'],
    suitableGoals: ['GENERAL_FITNESS', 'CALISTHENICS', 'SPORT_PERFORMANCE', 'ENDURANCE'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 8, hypertrophy: 12, fitness: 15, endurance: 20, calisthenics: 12, sport: 15 },
    defaultRestSeconds: 45,
  },
  {
    id: 'bw-plank',
    name: 'Forearm Plank',
    muscleGroup: 'CORE',
    measurementType: 'DURATION',
    equipmentRequired: 'NONE',
    instructions: 'Forearms parallel, elbows directly below shoulders, brace abs tightly without sagging hips.',
    alternative: 'Knee Forearm Plank',
    contraindications: [],
    suitableGoals: ['STRENGTH', 'GENERAL_FITNESS', 'ENDURANCE', 'CALISTHENICS', 'SPORT_PERFORMANCE'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 35, hypertrophy: 45, fitness: 40, endurance: 60, calisthenics: 50, sport: 45 },
    defaultRestSeconds: 45,
  },
  {
    id: 'bw-side-plank',
    name: 'Side Plank',
    muscleGroup: 'CORE',
    measurementType: 'DURATION',
    equipmentRequired: 'NONE',
    instructions: 'Elbow directly under shoulder, stack feet or stagger, lift pelvis into a straight diagonal line.',
    alternative: 'Knees-Grounded Side Plank',
    contraindications: ['SHOULDER_IMPINGEMENT'],
    suitableGoals: ['STRENGTH', 'GENERAL_FITNESS', 'ENDURANCE', 'CALISTHENICS', 'SPORT_PERFORMANCE'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 25, hypertrophy: 35, fitness: 30, endurance: 45, calisthenics: 35, sport: 35 },
    defaultRestSeconds: 45,
  },
  {
    id: 'bw-dead-bug',
    name: 'Dead Bug',
    muscleGroup: 'CORE',
    measurementType: 'REPS',
    equipmentRequired: 'NONE',
    instructions: 'Lie on back with knees at 90 degrees, press lumbar spine flat against floor, slowly extend opposite arm and leg.',
    alternative: 'Bent-Knee Tap Dead Bug',
    contraindications: [],
    suitableGoals: ['STRENGTH', 'GENERAL_FITNESS', 'CALISTHENICS', 'SPORT_PERFORMANCE', 'ENDURANCE'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 8, hypertrophy: 12, fitness: 12, endurance: 16, calisthenics: 12, sport: 12 },
    defaultRestSeconds: 45,
  },
  {
    id: 'bw-bird-dog',
    name: 'Bird-Dog Core Stability',
    muscleGroup: 'CORE',
    measurementType: 'REPS',
    equipmentRequired: 'NONE',
    instructions: 'Hands and knees on floor, extend opposite arm and leg parallel to floor, maintain zero pelvic tilt.',
    alternative: 'Quadruped Arm Reach Only',
    contraindications: [],
    suitableGoals: ['GENERAL_FITNESS', 'STRENGTH', 'SPORT_PERFORMANCE'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 8, hypertrophy: 12, fitness: 12, endurance: 16, calisthenics: 10, sport: 12 },
    defaultRestSeconds: 45,
  },
  {
    id: 'bw-hollow-body',
    name: 'Hollow Body Hold',
    muscleGroup: 'CORE',
    measurementType: 'DURATION',
    equipmentRequired: 'NONE',
    instructions: 'Lie flat, press lower back into ground, hover arms and feet with locked legs into a shallow banana shape.',
    alternative: 'Tuck Hollow Hold with Knees to Chest',
    contraindications: ['LOWER_BACK'],
    suitableGoals: ['CALISTHENICS', 'STRENGTH', 'SPORT_PERFORMANCE'],
    experienceMin: 'INTERMEDIATE',
    defaultReps: { strength: 20, hypertrophy: 30, fitness: 25, endurance: 40, calisthenics: 35, sport: 30 },
    defaultRestSeconds: 60,
  },
  {
    id: 'bw-mountain-climbers',
    name: 'Mountain Climbers',
    muscleGroup: 'CARDIO',
    measurementType: 'DURATION',
    equipmentRequired: 'NONE',
    instructions: 'Hold push-up plank position, alternate driving knees toward chest at brisk tempo without bouncing hips.',
    alternative: 'Slow Marching Plank Steps',
    contraindications: ['WRIST_DISCOMFORT', 'KNEE_PAIN'],
    suitableGoals: ['ENDURANCE', 'GENERAL_FITNESS', 'SPORT_PERFORMANCE'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 20, hypertrophy: 30, fitness: 30, endurance: 45, calisthenics: 30, sport: 35 },
    defaultRestSeconds: 45,
  },
  {
    id: 'bw-bear-crawl-hold',
    name: 'Bear Crawl Isometric Hold',
    muscleGroup: 'FULL_BODY',
    measurementType: 'DURATION',
    equipmentRequired: 'NONE',
    instructions: 'On all fours, elevate knees exactly 1-2 inches above floor, keep back flat like a tabletop.',
    alternative: 'Standard High Plank Hold',
    contraindications: ['WRIST_DISCOMFORT'],
    suitableGoals: ['CALISTHENICS', 'SPORT_PERFORMANCE', 'GENERAL_FITNESS'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 25, hypertrophy: 35, fitness: 30, endurance: 45, calisthenics: 35, sport: 35 },
    defaultRestSeconds: 45,
  },

  // ==========================================
  // HOME WITH EQUIPMENT / GYM EXERCISES
  // ==========================================
  {
    id: 'db-goblet-squat',
    name: 'Dumbbell Goblet Squat',
    muscleGroup: 'LEGS',
    measurementType: 'WEIGHT_REPS',
    equipmentRequired: 'DUMBBELLS',
    instructions: 'Hold dumbbell vertically at chest, descend into deep squat with vertical torso, drive through heels.',
    alternative: 'Bodyweight Squat',
    contraindications: ['KNEE_PAIN'],
    suitableGoals: ['STRENGTH', 'MUSCLE_GROWTH', 'GENERAL_FITNESS'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 6, hypertrophy: 10, fitness: 12, endurance: 15, calisthenics: 8, sport: 10 },
    defaultRestSeconds: 75,
  },
  {
    id: 'db-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift',
    muscleGroup: 'LEGS',
    measurementType: 'WEIGHT_REPS',
    equipmentRequired: 'DUMBBELLS',
    instructions: 'Slight knee bend, hinge backward at hips, lower dumbbells along shins until hamstring stretch, stand tall.',
    alternative: 'Bodyweight Glute Bridge',
    contraindications: ['LOWER_BACK'],
    suitableGoals: ['STRENGTH', 'MUSCLE_GROWTH', 'GENERAL_FITNESS', 'SPORT_PERFORMANCE'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 6, hypertrophy: 10, fitness: 12, endurance: 15, calisthenics: 8, sport: 10 },
    defaultRestSeconds: 75,
  },
  {
    id: 'db-bench-press',
    name: 'Dumbbell Bench Press',
    muscleGroup: 'CHEST',
    measurementType: 'WEIGHT_REPS',
    equipmentRequired: 'DUMBBELLS',
    instructions: 'Lie on flat bench, lower dumbbells with elbows at 45 degrees until deep chest stretch, press to lockout.',
    alternative: 'Standard Floor Push-Ups',
    contraindications: ['SHOULDER_IMPINGEMENT'],
    suitableGoals: ['STRENGTH', 'MUSCLE_GROWTH', 'GENERAL_FITNESS'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 6, hypertrophy: 10, fitness: 12, endurance: 15, calisthenics: 8, sport: 8 },
    defaultRestSeconds: 75,
  },
  {
    id: 'db-row',
    name: 'One-Arm Dumbbell Row',
    muscleGroup: 'BACK',
    measurementType: 'WEIGHT_REPS',
    equipmentRequired: 'DUMBBELLS',
    instructions: 'Hinge forward with flat back, pull dumbbell toward hip pocket, squeeze lat and retract scapula.',
    alternative: 'Prone Superman Squeeze',
    contraindications: [],
    suitableGoals: ['STRENGTH', 'MUSCLE_GROWTH', 'GENERAL_FITNESS', 'SPORT_PERFORMANCE'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 6, hypertrophy: 10, fitness: 12, endurance: 15, calisthenics: 8, sport: 10 },
    defaultRestSeconds: 60,
  },
  {
    id: 'db-overhead-press',
    name: 'Dumbbell Standing Overhead Press',
    muscleGroup: 'SHOULDERS',
    measurementType: 'WEIGHT_REPS',
    equipmentRequired: 'DUMBBELLS',
    instructions: 'Brace core and glutes, press dumbbells vertically overhead without arching lower back.',
    alternative: 'Incline Push-Ups',
    contraindications: ['SHOULDER_IMPINGEMENT', 'LOWER_BACK'],
    suitableGoals: ['STRENGTH', 'MUSCLE_GROWTH', 'SPORT_PERFORMANCE'],
    experienceMin: 'BEGINNER',
    defaultReps: { strength: 6, hypertrophy: 8, fitness: 10, endurance: 12, calisthenics: 8, sport: 8 },
    defaultRestSeconds: 75,
  },
  {
    id: 'pull-up-bar',
    name: 'Overhand Pull-Up',
    muscleGroup: 'BACK',
    measurementType: 'REPS',
    equipmentRequired: 'PULL_UP_BAR',
    instructions: 'Hang from bar with overhand grip, pull elbows down toward hips until chin clears bar, controlled descent.',
    alternative: 'Doorway Row or Inverted Bodyweight Row',
    contraindications: ['SHOULDER_IMPINGEMENT'],
    suitableGoals: ['STRENGTH', 'MUSCLE_GROWTH', 'CALISTHENICS', 'SPORT_PERFORMANCE'],
    experienceMin: 'INTERMEDIATE',
    defaultReps: { strength: 4, hypertrophy: 8, fitness: 8, endurance: 12, calisthenics: 8, sport: 6 },
    defaultRestSeconds: 90,
  },
  {
    id: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    muscleGroup: 'LEGS',
    measurementType: 'WEIGHT_REPS',
    equipmentRequired: 'BARBELL',
    instructions: 'Bar resting across upper traps, brace core with Valsalva maneuver, break at hips and knees to parallel, drive up.',
    alternative: 'Dumbbell Goblet Squat',
    contraindications: ['KNEE_PAIN', 'LOWER_BACK'],
    suitableGoals: ['STRENGTH', 'MUSCLE_GROWTH', 'SPORT_PERFORMANCE'],
    experienceMin: 'INTERMEDIATE',
    defaultReps: { strength: 5, hypertrophy: 8, fitness: 10, endurance: 12, calisthenics: 6, sport: 6 },
    defaultRestSeconds: 120,
  },
  {
    id: 'barbell-deadlift',
    name: 'Barbell Conventional Deadlift',
    muscleGroup: 'BACK',
    measurementType: 'WEIGHT_REPS',
    equipmentRequired: 'BARBELL',
    instructions: 'Feet hip-width under bar, grip bar firmly, engage lats, push floor away through midfoot, lock out hips.',
    alternative: 'Dumbbell Romanian Deadlift',
    contraindications: ['LOWER_BACK'],
    suitableGoals: ['STRENGTH', 'MUSCLE_GROWTH', 'SPORT_PERFORMANCE'],
    experienceMin: 'INTERMEDIATE',
    defaultReps: { strength: 4, hypertrophy: 6, fitness: 8, endurance: 10, calisthenics: 5, sport: 5 },
    defaultRestSeconds: 120,
  },
];
